-- Additive migration. Change mac_ only if the site uses another prefix.
CREATE TABLE IF NOT EXISTS mac_xb_ads (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 slot VARCHAR(40) NOT NULL,
 title VARCHAR(120) NOT NULL DEFAULT '',
 image_url VARCHAR(1024) NOT NULL,
 target_url VARCHAR(1024) NOT NULL DEFAULT '',
 enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
 sort_order INT NOT NULL DEFAULT 0,
 starts_at BIGINT NULL, ends_at BIGINT NULL,
 impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
 clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
 created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
 INDEX(slot,enabled,sort_order), INDEX(starts_at,ends_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS mac_xb_stats_daily (
 stat_date DATE NOT NULL PRIMARY KEY,
 plays BIGINT UNSIGNED NOT NULL DEFAULT 0,
 play_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0,
 unique_users BIGINT UNSIGNED NOT NULL DEFAULT 0,
 danmaku BIGINT UNSIGNED NOT NULL DEFAULT 0,
 ad_impressions BIGINT UNSIGNED NOT NULL DEFAULT 0,
 ad_clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
 updated_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
